from PIL import Image

# 1. Configuration ( match Verilog parameters)
WIDTH = 735
HEIGHT = 511
INPUT_BIN = "edge_output.bin"
OUTPUT_IMAGE = "edge_result.png"

# 2. Create a new grayscale image
img = Image.new('L', (WIDTH, HEIGHT))

# 3. Read binary file and map to pixels
try:
    with open(INPUT_BIN, "r") as f:
        lines = f.readlines()

    pixel_count = 0
    for line in lines:
        line = line.strip()
        
        # Skip empty lines, comments, or address markers generated by the simulator
        if not line or line.startswith('//') or line.startswith('@'):
            continue
            
        if pixel_count >= WIDTH * HEIGHT:
            break
            
        # Treat '1' as white (255) and anything else ('0', 'x', 'z') as black (0)
        pixel_color = 255 if line == '1' else 0
        
        x = pixel_count % WIDTH
        y = pixel_count // WIDTH
        img.putpixel((x, y), pixel_color)
        
        pixel_count += 1

    # 4. Save the image
    img.save(OUTPUT_IMAGE)
    print(f"Success! Edge detection image saved to {OUTPUT_IMAGE}")

except FileNotFoundError:
    print(f"Error: Could not find {INPUT_BIN}. Make sure the simulation finished.")